### ISSUE TITLE
bits/stdc++.h

### ISSUE THREAD

**Issue by ppenzin** [compiler-tree-technologies/fc#1]
`stdc++.h` is a GCC-specific header which is not available on Windows and BSD-based systems by default, build steps from the readme would not be reproducible on those systems.

A separate issue is that use of this header potentially increases compilation time, though I cannot provide any numbers, as I don't have experience with it.

Non-standard system headers can pose an issue for adoption, but that is a trade off that every project makes individually :)

**Comment by compiler-tree** [comment]
Thank you !!. We will look into it and try to fix it soon.

Thanks,
-Prashanth
